name: CI Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

env:
  DB_HOST: localhost
  DB_PORT: 3306
  DB_USERNAME: root
  DB_PASSWORD: secret
  DB_NAME: mysql
  PORT: 3000
  JWT_SECRET: test-secret
  ACCESS_TOKEN_VALIDITY_DURATION_IN_SEC: 1200
  HASH_SALT: 8

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Lint & Format
        run: |
          npm run lint
          npm run format

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test:cov
